#!/usr/bin/python

import sys, re

SPLIT=re.compile(r"\s*,\s*")

class Alias:
    def __init__(self, name, cat, subcat, lcat):
        self.name = name
        self.cat = int(cat)
        self.subcat = int(subcat)
        self.lcat = int(lcat)

# Read the aliases
aliases = []
state = 0
for line in sys.stdin:
    line = line.strip()
    if state == 0:
        if line == "%%":
            state = 1
        continue
    if state == 1:
        if line == "%%":
            state = 2
            continue
        if line.startswith("#"): continue
        if len(line) == 0: continue
        vals = SPLIT.split(line)
        if len(vals) != 4:
            raise RuntimeError, "Cannot parse line '%s'" % line
        aliases.append(Alias(*vals))
aliases.sort(key=lambda x: x.name)

fh = open("template-aliases.tex", "w")

print >>fh, r"""
\begin{scriptsize}
\begin{tabular}{|l|r|r|r|}
\hline
{\em Name} & {\em Category} & {\em Subcategory} & {\em Local category} \\
\hline
"""

for a in aliases:
    print >>fh, r"%s & %d & %d & %d \\" % (a.name, a.cat, a.subcat, a.lcat)

print >>fh, r"""
\hline
\end{tabular}
\end{scriptsize}
"""

fh.close()

