#!/bin/bash

TOP_SRCDIR=$(cd $(dirname $0) && pwd)
export LD_LIBRARY_PATH="$TOP_SRCDIR/dballe:$LD_LIBRARY_PATH"
export WREPORT_EXTRA_TABLES=$TOP_SRCDIR/tables
export DBA_REPINFO=$TOP_SRCDIR/tables/repinfo.csv
export DBA_TABLES=$TOP_SRCDIR/tables/
export PYTHONPATH=$TOP_SRCDIR/python/.libs:$TOP_SRCDIR/python/
export PATH="$TOP_SRCDIR/src:$PATH"

exec "$TOP_SRCDIR"/libtool --mode=execute "$@"
