#!/bin/sh

TOP_SRCDIR=$(cd $(dirname $0) && pwd)
export LD_LIBRARY_PATH="$TOP_SRCDIR/dballe:$LD_LIBRARY_PATH"
export WREPORT_EXTRA_TABLES=$TOP_SRCDIR/tables

for conffile in ./run-check.conf .git/run-check.conf
do
	if [ -f "$conffile" ]
	then
		. "$conffile"
		export DBA_DB
		export DBA_DB_SQLITE
		export DBA_DB_POSTGRESQL
		export DBA_DB_MYSQL
		break
	fi
done

exec make check "$@"
