#!/bin/sh

for conffile in ./run-check.conf .git/run-check.conf
do
	if [ -f "$conffile" ]
	then
		. "$conffile"
		export DBA_DB
		export DBA_DB_SQLITE
		export DBA_DB_POSTGRESQL
		export DBA_DB_MYSQL
		export DBA_DB_ODBC
		break
	fi
done

exec make check "$@"
