#!/bin/sh -ue

WORKDIR=`mktemp -d`
cp provami.py "$WORKDIR/provami"
cp $0 "$WORKDIR/"
cd "$WORKDIR/"

help2man -n "Manipulate georeferentiated raster image files" --no-info -i $0 -o provami.1 ./provami

cd -
cp "$WORKDIR/provami.1" .
rm -rf "$WORKDIR"

exit 0

[SEE ALSO]
