#!/bin/sh

# Run provami in a bit of a test environment

if [ "$1" = "clean" ]
then
	rm -f db.sqlite dballe
else
	if ! [ -e db.sqlite ]
	then
		eatmydata dbadb import --wipe-first --dsn=sqlite:db.sqlite ../extra/bufr/*.bufr
	fi
	if ! [ -e dballe ]
	then
		ln -s ../python dballe
	fi
	if [ -z "$DEBUGGER" ]
	then
		./provami.py --dsn=sqlite:db.sqlite
	else
		$DEBUGGER python ./provami.py --dsn=sqlite:db.sqlite
	fi
fi
