#!/usr/bin/perl -w

use strict;
use warnings;

sub make_key($$)
{
	my ($x, $y) = @_;
	return sprintf('"\x%02x\x%02x"', $x, $y);
}

sub make_val($$)
{
	my ($x, $y) = @_;

	if (defined $x)
	{
		return ($x << 8) + $y;
	} else {
		return 0;
	}

}

while (<>)
{
	s/^!\s+B(\d\d)(\d\d\d)\s*,\s*(B(\d\d)(\d\d\d))?\s*$/
		make_key($1, $2).", ".make_val($4, $5)."\n"/e;
	print;
}
