#!/bin/sh -ue

PKG=$1
shift

TAGLOCATIONS=""
for p in core bufrex msg db
do
	if [ $PKG = libdballe-$p ]
	then
		break
	else
		TAGLOCATIONS="$TAGLOCATIONS -l libdballe-$p.doxytags@../../libdballe-$p-doc/html"
	fi
done

SRCDIR=doc/${PKG}dox_html
DESTDIR=debian/libdballe-${PKG}-doc/usr/share/doc/libdballe-${PKG}-doc/html

install -d -o root -g root -m 755 $DESTDIR
find $SRCDIR -type f -exec install -o root -g root -m 0644 '{}' $DESTDIR/ ';'
cd $DESTDIR
if [ -f ./installdox ]
then
	echo Running ./installdox $TAGLOCATIONS "$@"
	perl ./installdox $TAGLOCATIONS "$@"
fi

exit 0
