#!/bin/sh -ue

SRC=$1
shift
PKG=$1
shift

TAGLOCATIONS=""
for p in libdballe-core libdballe-bufrex libdballe-msg libdballe-db
do
	if [ $PKG = $p-dev ]
	then
		break
	else
		TAGLOCATIONS="$TAGLOCATIONS -l $p.doxytags@../../$p/html"
	fi
done

SRCDIR=doc/$SRC
DESTDIR=debian/$PKG/usr/share/doc/$PKG/html

install -d -o root -g root -m 755 $DESTDIR
find $SRCDIR -type f -exec install -o root -g root -m 0644 '{}' $DESTDIR/ ';'
cd $DESTDIR
if [ -f ./installdox ]
then
	echo Running ./installdox $TAGLOCATIONS "$@"
	perl ./installdox $TAGLOCATIONS "$@"
fi

exit 0
