libdballeFortranbindings: binding.cc File Reference
binding.cc File Reference
Dballe fortran bindings
Simplified interface for Dballe.
#include "config.h"
#include "dballe/fortran/msgapi.h"
#include "dballe/fortran/dbapi.h"
#include "dballe/fortran/traced.h"
#include "dballe/core/var.h"
#include "dballe/db/db.h"
#include <cstring>
#include <limits.h>
#include <float.h>
#include "handles.h"
#include "error.h"
Macros
#define MISSING_BYTE SCHAR_MAX
#define MISSING_INT INT_MAX
#define MISSING_REAL FLT_MAX
#define MISSING_DOUBLE DBL_MAX
#define MAX_SIMPLE 50
#define MAX_SESSION 10
Functions
Session routines
These routines are used to begin and end working sessions with DB-All.e.
int idba_connect (int *dbahandle, const char *url)
Connect to the database.
int idba_disconnect (int *dbahandle)
Disconnect from the database.
int idba_begin (int dbahandle, int *handle, const char *anaflag, const char *dataflag, const char *attrflag)
Open a new session.
int idba_begin_messages (int *handle, const char *filename, const char *mode, const char *type)
Start working with a message file.
int idba_commit (int *handle)
Close a session.
Input/output routines
These routines are used to set the input and read the output of action routines.
int idba_seti (int handle, const char *parameter, const int *value)
Set an integer value in input.
int idba_setb (int handle, const char *parameter, const unsigned char *value)
Set a byte value in input.
int idba_setr (int handle, const char *parameter, const float *value)
Set a real value in input.
int idba_setd (int handle, const char *parameter, const double *value)
Set a real*8 value in input.
int idba_setc (int handle, const char *parameter, const char *value)
Set a character value in input.
int idba_enqi (int handle, const char *parameter, int *value)
Read an integer value from the output.
int idba_enqb (int handle, const char *parameter, unsigned char *value)
Read a byte value from the output.
int idba_enqr (int handle, const char *parameter, float *value)
Read a real value from the output.
int idba_enqd (int handle, const char *parameter, double *value)
Read a real*8 value from the output.
int idba_enqc (int handle, const char *parameter, char *value, unsigned value_len)
Read a character value from the output.
int idba_unset (int handle, const char *parameter)
Remove one value from the input.
int idba_unsetb (int handle)
Remove all Bxxyyy values from the input.
int idba_unsetall (int handle)
Completely clear the input, removing all values.
int idba_set_station_context (int handle)
Signal that the input values that are set are related to station values instead of normal variables.
Input/output shortcuts
The following routines are shortcuts for common combinations of Input/Output routines.
int idba_setlevel (int handle, int ltype1, int l1, int ltype2, int l2)
Set all level information.
int idba_settimerange (int handle, int ptype, int p1, int p2)
Set all time range information.
int idba_setdate (int handle, int year, int month, int day, int hour, int min, int sec)
Set all date information.
int idba_setdatemin (int handle, int year, int month, int day, int hour, int min, int sec)
Set the minimum date for a query.
int idba_setdatemax (int handle, int year, int month, int day, int hour, int min, int sec)
Set the maximum date for a query.
int idba_enqlevel (int handle, int *ltype1, int *l1, int *ltype2, int *l2)
Read all level information.
int idba_enqtimerange (int handle, int *ptype, int *p1, int *p2)
Read all time range information.
int idba_enqdate (int handle, int *year, int *month, int *day, int *hour, int *min, int *sec)
Read all date information.
Action routines
int idba_reinit_db (int handle, const char *repinfofile)
Reinitialize the database, removing all data and loading report information.
int idba_query_stations (int handle, int *count)
Query the stations in the database.
int idba_next_station (int handle)
Retrieve the data about one station.
int idba_query_data (int handle, int *count)
Query the data in the database.
int idba_next_data (int handle, char *parameter, int parameter_len)
Retrieve the data about one value.
int idba_insert_data (int handle)
Insert a new value in the database.
int idba_remove_data (int handle)
Remove from the database all values that match the query.
int idba_remove_all (int handle)
Remove all values from the database.
int idba_query_attributes (int handle, int *count)
Query attributes about a variable.
int idba_next_attribute (int handle, char *parameter, unsigned parameter_len)
Retrieve one attribute from the result of idba_query_attributes().
int idba_insert_attributes (int handle)
Insert new attributes for a variable.
int idba_remove_attributes (int handle)
Remove attribute information for a variable.
Message routines
int idba_messages_open_input (int handle, const char *filename, const char *mode, const char *format, int simplified)
Open a BUFR, or CREX file for reading.
int idba_messages_open_output (int handle, const char *filename, const char *mode, const char *format)
Open a BUFR, or CREX file for writing.
int idba_messages_read_next (int handle, int *found)
Read the next message and import it in the database.
int idba_messages_write_next (int handle, const char *template_name)
Export the data from the database that match the current query and add them to the current message.
Pretty-printing routines
int idba_describe_level (int handle, int ltype1, int l1, int ltype2, int l2, char *result, unsigned result_len)
Format the description of a level given its value.
int idba_describe_timerange (int handle, int ptype, int p1, int p2, char *result, unsigned result_len)
Format the description of a time range given its value.
int idba_describe_var (int handle, const char *varcode, const char *value, char *result, unsigned result_len)
Format the description of a variable given its varcode and its value.
Deprecated aliases
The following routines are deprecated compatibility aliases for other API functions.
int idba_presentati (int *dbahandle, const char *url)
Deprecated compatibility version of idba_connect()
int idba_arrivederci (int *dbahandle)
Deprecated compatibility version of idba_disconnect()
int idba_preparati (int dbahandle, int *handle, const char *anaflag, const char *dataflag, const char *attrflag)
Deprecated compatibility version of idba_begin()
int idba_messaggi (int *handle, const char *filename, const char *mode, const char *type)
Deprecated compatibility version of idba_begin_messages()
int idba_fatto (int *handle)
Deprecated compatibility version of idba_commit()
int idba_setcontextana (int handle)
Deprecated compatibility version of idba_set_station_context()
int idba_scopa (int handle, const char *repinfofile)
Deprecated compatibility version of idba_reinit_db()
int idba_quantesono (int handle, int *count)
Deprecated compatibility version of idba_query_stations()
int idba_elencamele (int handle)
Deprecated compatibility version of idba_next_station()
int idba_voglioquesto (int handle, int *count)
Deprecated compatibility version of idba_query_data()
int idba_dammelo (int handle, char *parameter, int parameter_len)
Deprecated compatibility version of idba_next_data()
int idba_prendilo (int handle)
Deprecated compatibility version of idba_insert_data()
int idba_dimenticami (int handle)
Deprecated compatibility version of idba_remove_data()
int idba_voglioancora (int handle, int *count)
Deprecated compatibility version of idba_query_attributes()
int idba_ancora (int handle, char *parameter, unsigned parameter_len)
Deprecated compatibility version of idba_next_attribute()
int idba_critica (int handle)
Deprecated compatibility version of idba_insert_attributes()
int idba_scusa (int handle)
Deprecated compatibility version of idba_remove_attributes()
int idba_spiegal (int handle, int ltype1, int l1, int ltype2, int l2, char *result, unsigned result_len)
Deprecated compatibility version of idba_describe_level()
int idba_spiegat (int handle, int ptype, int p1, int p2, char *result, unsigned result_len)
Deprecated compatibility version of idba_describe_timerange()
int idba_spiegab (int handle, const char *varcode, const char *value, char *result, unsigned result_len)
Deprecated compatibility version of idba_describe_var()
Variables
struct fortran::Handler< HSession, MAX_SESSION > hsess
struct fortran::Handler< HSimple, MAX_SIMPLE > hsimp
Detailed Description
Simplified interface for Dballe.
Every function returns an error indicator, which is 0 if no error happened, or 1 if there has been an error.
When an error happens, the functions in error.c can be used to get detailed informations about it.
Function Documentation
idba_begin()
int idba_begin (int dbahandle, int * handle, const char * anaflag, const char * dataflag, const char * attrflag)
Open a new session.
You can call idba_begin() many times and get more handles. This allows to perform many operations on the database at the same time.
idba_begin() has three extra parameters that can be used to limit write operations on the database, as a limited protection against programming errors:
anaflag controls access to station value records and can have these values:
"read" station records cannot be inserted.
"write" it is possible to insert and delete pseudoana records.
dataflag controls access to observed data and can have these values:
"read" data cannot be modified in any way.
"add" data can be added to the database, but existing data cannot be modified. Deletions are disabled. This is used to insert new data in the database while preserving the data that was already present in it.
"write" data can freely be added, overwritten and deleted.
attrflag controls access to data attributes and can have these values:
"read" attributes cannot be modified in any way.
"write" attributes can freely be added, overwritten and deleted.
Note that some combinations of parameters are illegal, such as anaflag=read and dataflag=add (when adding a new data, it's sometimes necessary to insert new pseudoana records), or dataflag=rewrite and attrflag=read (when deleting data, their attributes are deleted as well).
Parameters
dbahandle The main DB-ALLe connection handle
Return values
handle The session handle created by the function
Parameters
anaflag station values access level
dataflag data values access level
attrflag attribute access level
Returns
The error indication for the function.
Referenced by idba_preparati().
idba_begin_messages()
int idba_begin_messages (int * handle, const char * filename, const char * mode, const char * type)
Start working with a message file.
Return values
handle The session handle returned by the function
Parameters
filename Name of the file to open
mode File open mode. It can be "r" for read, "w" for write (the old file is deleted), "a" for append
type Format of the data in the file. It can be: "BUFR", "CREX", "AUTO" (autodetect, read only)
Returns
The error indication for the function.
Referenced by idba_messaggi().
idba_commit()
int idba_commit (int * handle)
Close a session.
Parameters
handle Handle to the session to be closed.
Referenced by idba_fatto().
idba_connect()
int idba_connect (int * dbahandle, const char * url)
Connect to the database.
This function can be called more than once to connect to different databases at the same time.
The function expects to find a properly initialised DB-All.e database. Append &wipe=true to the end of the url to wipe any existing DB-All.e information from the database if it exists, then recreate it from scratch.
Parameters
url The URL of the database to use
user Used in the past, now it is ignored.
password Used in the past, now it is ignored.
Return values
dbahandle The database handle that can be passed to idba_begin to work with the database.
Returns
The error indication for the function.
idba_describe_level()
int idba_describe_level (int handle, int ltype1, int l1, int ltype2, int l2, char * result, unsigned result_len)
Format the description of a level given its value.
Parameters
handle Handle to a DB-All.e session
ltype1 Level type to set in the input record
l1 L1 to set in the input record
ltype2 Level type to set in the input record
l2 L2 to set in the input record
Return values
result The string with the description of the level.
Returns
The error indication for the function.
Referenced by idba_spiegal().
idba_describe_timerange()
int idba_describe_timerange (int handle, int ptype, int p1, int p2, char * result, unsigned result_len)
Format the description of a time range given its value.
Parameters
handle Handle to a DB-All.e session
ptype P indicator to set in the input record
p1 P1 to set in the input record
p2 P2 to set in the input record
Return values
result The string with the description of the time range.
Returns
The error indication for the function.
Referenced by idba_spiegat().
idba_describe_var()
int idba_describe_var (int handle, const char * varcode, const char * value, char * result, unsigned result_len)
Format the description of a variable given its varcode and its value.
Parameters
handle Handle to a DB-All.e session
varcode B table code of the variable ("Bxxyyy")
value Value of the variable, as read with idba_enqc()
Return values
result The string with the description of the time range.
Returns
The error indication for the function.
Referenced by idba_spiegab().
idba_disconnect()
int idba_disconnect (int * dbahandle)
Disconnect from the database.
Parameters
dbahandle The database handle to close.
Referenced by idba_arrivederci().
idba_enqb()
int idba_enqb (int handle, const char * parameter, unsigned char * value)
Read a byte value from the output.
Parameters
handle Handle to a DB-All.e session
parameter Parameter to query. It can be the code of a WMO variable prefixed by "B" (such as "B01023"); the code of a QC value prefixed by "*B" (such as "*B01023") or a keyword among the ones defined in fapi_parms.md
value Where the value will be returned
Returns
The error indicator for the function
idba_enqc()
int idba_enqc (int handle, const char * parameter, char * value, unsigned value_len)
Read a character value from the output.
Parameters
handle Handle to a DB-All.e session
parameter Parameter to query. It can be the code of a WMO variable prefixed by "B" (such as "B01023"); the code of an attribute prefixed by "*B" (such as "*B01023") or a keyword among the ones defined in fapi_parms.md
value Where the value will be returned
Returns
The error indicator for the function
idba_enqd()
int idba_enqd (int handle, const char * parameter, double * value)
Read a real*8 value from the output.
Parameters
handle Handle to a DB-All.e session
parameter Parameter to query. It can be the code of a WMO variable prefixed by "B" (such as "B01023"); the code of a QC value prefixed by "*B" (such as "*B01023") or a keyword among the ones defined in fapi_parms.md
value Where the value will be returned
Returns
The error indicator for the function
idba_enqdate()
int idba_enqdate (int handle, int * year, int * month, int * day, int * hour, int * min, int * sec)
Read all date information.
Parameters
handle Handle to a DB-All.e session
Return values
year Year from the output record
month Month the output record
day Day the output record
hour Hour the output record
min Minute the output record
sec Second the output record
Returns
The error indicator for the function
idba_enqi()
int idba_enqi (int handle, const char * parameter, int * value)
Read an integer value from the output.
Parameters
handle Handle to a DB-All.e session
parameter Parameter to query. It can be the code of a WMO variable prefixed by "B" (such as "B01023"); the code of a QC value prefixed by "*B" (such as "*B01023") or a keyword among the ones defined in fapi_parms.md
value Where the value will be returned
Returns
The error indicator for the function
idba_enqlevel()
int idba_enqlevel (int handle, int * ltype1, int * l1, int * ltype2, int * l2)
Read all level information.
Parameters
handle Handle to a DB-All.e session
Return values
ltype1 Type of the first level from the output record
l1 L1 from the output record
ltype2 Type of the second level from the output record
l2 L2 from the output record
Returns
The error indicator for the function
idba_enqr()
int idba_enqr (int handle, const char * parameter, float * value)
Read a real value from the output.
Parameters
handle Handle to a DB-All.e session
parameter Parameter to query. It can be the code of a WMO variable prefixed by "B" (such as "B01023"); the code of a QC value prefixed by "*B" (such as "*B01023") or a keyword among the ones defined in fapi_parms.md
value Where the value will be returned
Returns
The error indicator for the function
idba_enqtimerange()
int idba_enqtimerange (int handle, int * ptype, int * p1, int * p2)
Read all time range information.
Parameters
handle Handle to a DB-All.e session
Return values
ptype P indicator from the output record
p1 P1 from the output record
p2 P2 from the output record
Returns
The error indicator for the function
idba_insert_attributes()
int idba_insert_attributes (int handle)
Insert new attributes for a variable.
The variable is either:
the last variable returned by idba_next_data()
the last variable inserted by idba_insert_data()
the variable selected by settings *context_id and *var_related.
The attributes that will be inserted are all those set by the functions idba_seti(), idba_setc(), idba_setr(), idba_setd(), using an asterisk in front of the variable name.
Contrarily to idba_insert_data(), this function resets all the attribute information (and only attribute information) previously set in input, so the values to be inserted need to be explicitly set every time.
This function will fail if the database is open in attribute readonly mode, and it will refuse to overwrite existing values if the database is open in attribute add mode.
Parameters
handle Handle to a DB-All.e session
Returns
The error indicator for the function
Referenced by idba_critica().
idba_insert_data()
int idba_insert_data (int handle)
Insert a new value in the database.
This function will fail if the database is open in data readonly mode, and it will refuse to overwrite existing values if the database is open in data add mode.
If the database is open in station reuse mode, the station values provided on input will be used to create a station record if it is missing, but will be ignored if it is already present. If it is open in station rewrite mode instead, the station values on input will be used to replace all the existing station values.
Parameters
handle Handle to a DB-All.e session
Returns
The error indicator for the function
Referenced by idba_prendilo().
idba_messages_open_input()
int idba_messages_open_input (int handle, const char * filename, const char * mode, const char * format, int simplified)
Open a BUFR, or CREX file for reading.
Each session can only have one open input file: if one was previously open, it is closed before opening the new one.
Parameters
handle Handle to a DB-All.e session
filename The file name
mode The opening mode. See the mode parameter of libc's fopen() call for details.
format The file format ("BUFR", or "CREX")
simplified true if the file is imported in simplified mode, false if it is imported in precise mode. This controls approximating levels and time ranges to standard values.
Returns
The error indication for the function.
idba_messages_open_output()
int idba_messages_open_output (int handle, const char * filename, const char * mode, const char * format)
Open a BUFR, or CREX file for writing.
Each session can only have one open input file: if one was previously open, it is closed before opening the new one.
Parameters
handle Handle to a DB-All.e session
filename The file name
mode The opening mode. See the mode parameter of libc's fopen() call for details.
format The file format ("BUFR", or "CREX")
Returns
The error indication for the function.
idba_messages_read_next()
int idba_messages_read_next (int handle, int * found)
Read the next message and import it in the database.
The access mode of the session controls how data is imported:
station and data mode cannot be "read".
if data mode is "add", existing data will not be overwritten.
if attribute mode is "read", attributes will not be imported.
Parameters
handle Handle to a DB-All.e session
Return values
found True if a message has been imported, false if we are at the end of the input file.
Returns
The error indication for the function.
idba_messages_write_next()
int idba_messages_write_next (int handle, const char * template_name)
Export the data from the database that match the current query and add them to the current message.
Parameters
handle Handle to a DB-All.e session
template_name The template name used to decide the layout of variables in the messages that are exported.
Returns
The error indication for the function.
idba_next_attribute()
int idba_next_attribute (int handle, char * parameter, unsigned parameter_len)
Retrieve one attribute from the result of idba_query_attributes().
Parameters
handle Handle to a DB-All.e session
Return values
parameter Contains the ID of the parameter retrieved by this fetch
Returns
The error indicator for the function
Referenced by idba_ancora().
idba_next_data()
int idba_next_data (int handle, char * parameter, int parameter_len)
Retrieve the data about one value.
After invocation, the output record is filled with information about the value.
If there are no more values to read, the function will fail with DBA_ERR_NOTFOUND.
Parameters
handle Handle to a DB-All.e session
Return values
parameter Contains the variable code of the parameter retrieved by this fetch
Returns
The error indicator for the function
Referenced by idba_dammelo().
idba_next_station()
int idba_next_station (int handle)
Retrieve the data about one station.
After invocation, the output record is filled with information about the station and its station values.
If there are no more stations to read, the function will fail with DBA_ERR_NOTFOUND.
Parameters
handle Handle to a DB-All.e session
Returns
The error indicator for the function
Referenced by idba_elencamele().
idba_query_attributes()
int idba_query_attributes (int handle, int * count)
Query attributes about a variable.
The variable queried is either:
the last variable returned by idba_next_data()
the last variable inserted by idba_insert_data()
the variable selected by settings *context_id and *var_related.
Results are retrieved using idba_next_attribute().
Parameters
handle Handle to a DB-All.e session
Return values
count Number of values returned by the function
Returns
The error indicator for the function
Referenced by idba_voglioancora().
idba_query_data()
int idba_query_data (int handle, int * count)
Query the data in the database.
Results are retrieved using idba_next_data().
Results are sorted by (in order): ana_id, datetime, level, time range, varcode. The ana_id changes slowest, and the varcode changes fastest.
Ordering by ana_id effectively does grouping by station rather than ordering.
Sort order can change in the future, with the invariant that the slowest to change remains ana_id, followed by datetime, and the fastest to change remains the varcode.
Parameters
handle Handle to a DB-All.e session
Return values
count Number of values returned by the function
Returns
The error indicator for the function
Referenced by idba_voglioquesto().
idba_query_stations()
int idba_query_stations (int handle, int * count)
Query the stations in the database.
Results are retrieved using idba_next_station().
There is no guarantee on the ordering of results of query_stations/next_station.
Parameters
handle Handle to a DB-All.e session
count The count of elements
Returns
The error indicator for the function
Referenced by idba_quantesono().
idba_reinit_db()
int idba_reinit_db (int handle, const char * repinfofile)
Reinitialize the database, removing all data and loading report information.
It requires the database to be opened in rewrite mode.
Parameters
handle Handle to a DB-All.e session
repinfofile CSV file with the default report informations. See dba_reset() documentation for the format of the file.
Returns
The error indicator for the function
Referenced by idba_scopa().
idba_remove_all()
int idba_remove_all (int handle)
Remove all values from the database.
The difference with idba_reinit_db() is that it preserves the existing report information.
Parameters
handle Handle to a DB-All.e session
Returns
The error indicator for the function
idba_remove_attributes()
int idba_remove_attributes (int handle)
Remove attribute information for a variable.
The variable is either:
the last variable returned by idba_next_data()
the last variable inserted by idba_insert_data()
the variable selected by settings *context_id and *var_related.
The attribute informations to be removed are selected with:
idba_setc(handle, "*varlist", "*B33021,*B33003");
Parameters
handle Handle to a DB-All.e session
Returns
The error indicator for the function
Referenced by idba_scusa().
idba_remove_data()
int idba_remove_data (int handle)
Remove from the database all values that match the query.
This function will fail unless the database is open in data rewrite mode.
Parameters
handle Handle to a DB-All.e session
Returns
The error indicator for the function
Referenced by idba_dimenticami().
idba_set_station_context()
int idba_set_station_context (int handle)
Signal that the input values that are set are related to station values instead of normal variables.
Parameters
handle Handle to a DB-All.e session
Returns
The error indicator for the function
Referenced by idba_setcontextana().
idba_setb()
int idba_setb (int handle, const char * parameter, const unsigned char * value)
Set a byte value in input.
Parameters
handle Handle to a DB-All.e session
parameter Parameter to set. It can be the code of a WMO variable prefixed by "B" (such as "B01023"); the code of a QC value prefixed by "*B" (such as "*B01023") or a keyword among the ones defined in fapi_parms.md
value The value to assign to the parameter
Returns
The error indicator for the function
idba_setc()
int idba_setc (int handle, const char * parameter, const char * value)
Set a character value in input.
Parameters
handle Handle to a DB-All.e session
parameter Parameter to set. It can be the code of a WMO variable prefixed by "B" (such as "B01023"); the code of a QC value prefixed by "*B" (such as "*B01023") or a keyword among the ones defined in fapi_parms.md
value The value to assign to the parameter
Returns
The error indicator for the function
idba_setd()
int idba_setd (int handle, const char * parameter, const double * value)
Set a real*8 value in input.
Parameters
handle Handle to a DB-All.e session
parameter Parameter to set. It can be the code of a WMO variable prefixed by "B" (such as "B01023"); the code of a QC value prefixed by "*B" (such as "*B01023") or a keyword among the ones defined in fapi_parms.md
value The value to assign to the parameter
Returns
The error indicator for the function
idba_setdate()
int idba_setdate (int handle, int year, int month, int day, int hour, int min, int sec)
Set all date information.
Parameters
handle Handle to a DB-All.e session
year Year to set in the input record
month Month to set in the input
day Day to set in the input
hour Hour to set in the input
min Minute to set in the input
sec Second to set in the input
Returns
The error indicator for the function
idba_setdatemax()
int idba_setdatemax (int handle, int year, int month, int day, int hour, int min, int sec)
Set the maximum date for a query.
Parameters
handle Handle to a DB-All.e session
year Maximum year to set in the query
month Maximum month to set in the query
day Maximum day to set in the query
hour Maximum hour to set in the query
min Maximum minute to set in the query
sec Maximum second to set in the query
Returns
The error indicator for the function
idba_setdatemin()
int idba_setdatemin (int handle, int year, int month, int day, int hour, int min, int sec)
Set the minimum date for a query.
Parameters
handle Handle to a DB-All.e session
year Minimum year to set in the query
month Minimum month to set in the query
day Minimum day to set in the query
hour Minimum hour to set in the query
min Minimum minute to set in the query
sec Minimum second to set in the query
Returns
The error indicator for the function
idba_seti()
int idba_seti (int handle, const char * parameter, const int * value)
Set an integer value in input.
Parameters
handle Handle to a DB-All.e session
parameter Parameter to set. It can be the code of a WMO variable prefixed by "B" (such as "B01023"); the code of a QC value prefixed by "*B" (such as "*B01023") or a keyword among the ones defined in fapi_parms.md
value The value to assign to the parameter
Returns
The error indicator for the function
idba_setlevel()
int idba_setlevel (int handle, int ltype1, int l1, int ltype2, int l2)
Set all level information.
Parameters
handle Handle to a DB-All.e session
ltype1 Level type to set in the input record
l1 L1 to set in the input record
ltype2 Level type to set in the input record
l2 L2 to set in the input record
Returns
The error indicator for the function
idba_setr()
int idba_setr (int handle, const char * parameter, const float * value)
Set a real value in input.
Parameters
handle Handle to a DB-All.e session
parameter Parameter to set. It can be the code of a WMO variable prefixed by "B" (such as "B01023"); the code of a QC value prefixed by "*B" (such as "*B01023") or a keyword among the ones defined in fapi_parms.md
value The value to assign to the parameter
Returns
The error indicator for the function
idba_settimerange()
int idba_settimerange (int handle, int ptype, int p1, int p2)
Set all time range information.
Parameters
handle Handle to a DB-All.e session
ptype P indicator to set in the input record
p1 P1 to set in the input record
p2 P2 to set in the input record
Returns
The error indicator for the function
idba_unset()
int idba_unset (int handle, const char * parameter)
Remove one value from the input.
Parameters
handle Handle to a DB-All.e session
parameter Parameter to remove. It can be the code of a WMO variable prefixed by "B" (such as "B01023"); the code of a QC value prefixed by "*B" (such as "*B01023") or a keyword among the ones defined in fapi_parms.md
Returns
The error indicator for the function
idba_unsetall()
int idba_unsetall (int handle)
Completely clear the input, removing all values.
Parameters
handle Handle to a DB-All.e session
idba_unsetb()
int idba_unsetb (int handle)
Remove all Bxxyyy values from the input.
Parameters
handle Handle to a DB-All.e session